name: Check PHPUnit tests coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, json, dom, pdo, pdo_mysql
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit with coverage
        run: |
          composer test:coverage

      - name: Check coverage percentage
        uses: php-actions/phpunit-coverage-check@v2
        with:
          clover-file: ./.coverage-phpunit/coverage.xml
          min-coverage: 0
          fail-on-low-coverage: true

